import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/NavBar";
import GetStarted from "@/components/ui/GetStarted";
import Footer from "@/components/shared/Footer";
import Providers from "@/services/providers";
import ChatWidget from "@/components/ui/ChatBot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figtree = Figtree({
  subsets: ['latin'],
  variable: '--font-figtree',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} antialiased`}
      >
        <Providers>
        <Navbar />
          {children}
        <GetStarted />
        <Footer />
        <ChatWidget />
        </Providers>
      </body>
    </html>
  );
}
